language: node_js
node_js:
  - 11.13.0
script:
  - npm install --global workbox-cli
  - workbox generateSW workbox-config.js
deploy:
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: bsawa-staging
    region: eu-north-1
    acl: public_read
    on:
      branch: develop
  - provider: s3
    skip_cleanup: true
    access_key_id: $AWS_ACCESS_ID
    secret_access_key: $AWS_ACCESS_KEY
    bucket: bsawa-production
    region: eu-north-1
    acl: public_read
    on:
      branch: main
